---
  - name: Install dependencias
    apt:
      pkg:
      - apache2
      - ghostscript
      - mysql-server
      - libapache2-mod-php 
      - php 
      - php-bcmath 
      - php-curl 
      - php-imagick 
      - php-intl 
      - php-json 
      - php-mbstring 
      - php-mysql 
      - php-xml 
      - php-zip
      - python3-pymysql
      state: latest
      update_cache: yes
